"""
Evidently Monitoring Dashboard
===================================
Serves pre-generated Evidently HTML reports from the shared volume.
Reports are generated by the API service after retraining / drift simulation.
"""

import os

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse

REPORTS_PATH = os.environ.get("REPORTS_PATH", "/app/reports")

# LESSON POINT: Separating Concerns in MLOps Architecture
# It is a best practice to separate prediction services from administrative or monitoring
# services. The Evidently Monitoring Dashboard runs on its own port and relies on a shared Docker
# volume. The main API generates static HTML reports, and this app serves them. This keeps
# dependencies clean and ensures monitoring load doesn't impact production inference response times.
app = FastAPI(
    title="Titanic Monitoring Dashboard",
    description="Browse Evidently AI data-drift and performance reports.",
    version="1.0.0",
    root_path="/monitoring",
)


@app.get("/health", tags=["ops"])
def health():
    """Liveness probe."""
    return {"status": "healthy"}


@app.get("/", tags=["reports"])
def list_reports():
    """List all available Evidently reports (newest first)."""
    if not os.path.exists(REPORTS_PATH):
        return {"reports": [], "message": "No reports generated yet. Trigger /api/retrain or /api/simulate-drift."}

    reports = sorted(
        [f for f in os.listdir(REPORTS_PATH) if f.endswith(".html")],
        reverse=True,
    )
    return {
        "total": len(reports),
        "reports": reports,
        "hint": "GET /monitoring/report/{filename} to view a specific report.",
    }


@app.get("/report/{filename}", tags=["reports"])
def get_report(filename: str):
    """Serve a specific Evidently HTML report."""
    # Basic path-traversal guard
    if ".." in filename or "/" in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    filepath = os.path.join(REPORTS_PATH, filename)
    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail=f"Report '{filename}' not found")

    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    return HTMLResponse(content=content)
